apiVersion: v1
kind: Service
metadata:
  name: jenkinskubernetes-service
spec:
  type: NodePort
  selector:
    app: jenkinskubernetes
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30001  # You can access it at <NodeIP>:30001
